### ISSUE TITLE
Snmp exporter is still restarting with some ugly error

### ISSUE THREAD

**Issue by tom-i** [prometheus/snmp_exporter#1006]
### Host operating system: output of `uname -a`
`Linux HOSTNAME.cz.prod 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
### snmp_exporter version: output of `snmp_exporter -version`

```
# ./snmp_exporter --version
snmp_exporter, version 0.24.1 (branch: HEAD, revision: f8826bcfadf9d93df9516c660fdc1d503f4e0b95)
  build user:       root@6206907e6947
  build date:       20230901-07:37:50
  go version:       go1.21.0
  platform:         linux/amd64
  tags:             netgo
```
### What device/snmpwalk OID are you using?
Cisco, Viptela, HP VC, CheckPoint, Brocade
### What did you do that produced an error?
1. Copy snmp.yml
2. Restart snmp_exporter service
### What did you expect to see?
Proper functionality.
### What did you see instead?
In `journalctl -fu snmp_explorer.service` I see that snmp exporter is still restarting with some ugly error inside:
```
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: panic: Unknown index type DateAndTime
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: goroutine 192 [running]:
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: github.com/prometheus/snmp_exporter/collector.indexOidsAsString({0xc00198bf60, 0xc, 0x14}, {0xc000df0da0, 0xb}, 0x0, 0x0, 0x18?)
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:883 +0xb46
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: github.com/prometheus/snmp_exporter/collector.indexesToLabels({0xc00198bf60, 0xc, 0x14}, 0xc0010f6c80, 0xe96b08?, {0xc00004e220, {0xabd438, 0xc001186000}, {0xabc698, 0xc00118a000}, ...})
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:900 +0x16f
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: github.com/prometheus/snmp_exporter/collector.pduToSamples({0xc00198bf60, 0xc, 0x14}, 0xc001131a20, 0xc0010f6c80, 0xc001095280?, {0xab8320, 0xc0010bd0e0}, {0xc00004e220, {0xabd438, ...}, ...})
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:544 +0xa8
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: github.com/prometheus/snmp_exporter/collector.Collector.collect({{0xabc068, 0xc0010bcf00}, {0xc00098c086, 0xd}, 0xc0000b0360, {0xc00098c05f, 0xc}, {0xc00004e0f0, 0x1, 0x1}, ...}, ...)
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:432 +0xaf8
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: github.com/prometheus/snmp_exporter/collector.Collector.Collect.func1()
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:462 +0x290
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: created by github.com/prometheus/snmp_exporter/collector.Collector.Collect in goroutine 190
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[23209]: /app/collector/collector.go:456 +0xd9
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: snmp_exporter.service: main process exited, code=exited, status=2/INVALIDARGUMENT
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: Unit snmp_exporter.service entered failed state.
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: snmp_exporter.service failed.
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: snmp_exporter.service holdoff time over, scheduling restart.
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: Stopped SNMP Exporter.
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod systemd[1]: Started SNMP Exporter.
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[32348]: ts=2023-09-20T14:37:37.475Z caller=main.go:194 level=info msg="Starting snmp_exporter" version="(version=0.24.1, branch=HEAD, revision=f8826bcfadf9d93df9516c660fdc1d503f4e0b95)" concurrency=1
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[32348]: ts=2023-09-20T14:37:37.475Z caller=main.go:195 level=info build_context="(go=go1.21.0, platform=linux/amd64, user=root@6206907e6947, date=20230901-07:37:50, tags=netgo)"
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[32348]: ts=2023-09-20T14:37:37.559Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9116
zář 20 16:37:37 os01-cl0va3nzdj.cz.prod snmp_exporter[32348]: ts=2023-09-20T14:37:37.559Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9116
```

**Comment by SuperQ** [comment]
Can you please include a copy of your `snmp.yml` config? Otherwise there is no way to know what is wrong.

**Comment by tom-i** [comment]
@SuperQ np, but it has about 1MB :-/

**Comment by SuperQ** [comment]
I tried to reproduce your error and was not able to with the MIB walks you provided in the snmp.yml.

In your configuration, I do not see any use of `DateAndTime` in any index data, only as metric values.

Maybe your production copy of the snmp.yaml is corrupted?

**Comment by tom-i** [comment]
@SuperQ - you're right.. some part of my snmp.yml is broken.. especially part with `viptela_mib` OIDs.. I'll investigate it in near future. Thx for you hint ;)
