### ISSUE TITLE
IBM FC-Switches: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by mjtrangoni** [prometheus/snmp_exporter#59]
I have a `random` issue with the IBM Fibre-Channel Switches, using a renamed but cloned default module for the snmp_exporter.

Prometheus says: Error: `context deadline exceeded`, and snmp_exporter log this:
```
Sep 01 14:11:02 hostname snmp_exporter[1991]: 192.168.139.44 - - [01/Sep/2016 14:11:02] "GET /metrics?address=switch-4.localdomain&module=brocade HTTP/1.1" 200 -
Sep 01 14:11:02 hostname snmp_exporter[1991]: 192.168.139.44 - - [01/Sep/2016 14:11:02] "GET /metrics?address=switch-4.localdomain&module=brocade HTTP/1.1" 500 -
Sep 01 14:11:02 hostname snmp_exporter[1991]: Traceback (most recent call last):
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/SocketServer.py", line 568, in process_request
Sep 01 14:11:02 hostname snmp_exporter[1991]: self.finish_request(request, client_address)
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Sep 01 14:11:02 hostname snmp_exporter[1991]: self.RequestHandlerClass(request, client_address, self)
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib/python2.7/site-packages/snmp_exporter/http.py", line 70, in <lambda>
Sep 01 14:11:02 hostname snmp_exporter[1991]: handler = lambda *args, **kwargs: SnmpExporterHandler(config_path, *args, **kwargs)
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib/python2.7/site-packages/snmp_exporter/http.py", line 25, in __init__
Sep 01 14:11:02 hostname snmp_exporter[1991]: BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Sep 01 14:11:02 hostname snmp_exporter[1991]: self.finish()
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Sep 01 14:11:02 hostname snmp_exporter[1991]: self.wfile.close()
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Sep 01 14:11:02 hostname snmp_exporter[1991]: self.flush()
Sep 01 14:11:02 hostname snmp_exporter[1991]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Sep 01 14:11:02 hostname snmp_exporter[1991]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Sep 01 14:11:02 hostname snmp_exporter[1991]: error: [Errno 32] Broken pipe
```

With `2498_24e` and `2498_24g` (24 Ports) it happens randomly but not always. With the `2498_f48` it happens all the time.

I saw also that the headers are shown as footers if this error happens.

How can I debug it? Or how can I fix it?

OS: CentOS Linux release 7.2.1511 (Core)
Python: from System, 2.7.5
SNMP Exporter: 0.0.6

**Comment by RichiH** [comment]
As per https://github.com/prometheus/snmp_exporter/issues/53, the Python implementation will be replaced with Go. I suggest you wait until that time and then retry :)

**Comment by brian-brazil** [comment]
This smells like a timeout, try increasing the scrape_timeout on the Prometheus end.

**Comment by mjtrangoni** [comment]
Thanks @brian-brazil. It works now.
