### ISSUE TITLE
snmp_exporter - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by IAmMrTh** [prometheus/snmp_exporter#768]
Hey,

I wanted to set up the snmp_exporter for Prometheus. I created the snmp.yml file with the generator because the device i want to monitor has snmpV3. 

I am able to generate the YAML file. but when i want to open the metrics page over the http port 9116, with the Input 
Target: <IP of switch>
Module: if_mib
I always get the error:

`An error has occurred while serving metrics:

error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error getting target 192.168.50.203: recover: runtime error: invalid memory address or nil pointer dereference
Stack:goroutine 11 [running]:
github.com/gosnmp/gosnmp.(*GoSNMP).send.func1(0xc000a0f5c8)
	/go/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/marshal.go:326 +0xa5
panic(0x9e4880, 0xe89790)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gosnmp/gosnmp.(*GoSNMP).send(0xc000258000, 0xc000276000, 0xc0002a0201, 0x0, 0xb34ee0, 0xc00196ebf0)
	/go/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/marshal.go:372 +0x20e
github.com/gosnmp/gosnmp.(*GoSNMP).Get(0xc000258000, 0xc001806ff0, 0x1, 0x1, 0x0, 0x0, 0xc0002a01b0)
	/go/pkg/mod/github.com/gosnmp/gosnmp@v1.29.0/gosnmp.go:363 +0x159
main.ScrapeTarget(0xb40660, 0xc0019feb00, 0xc000820011, 0xe, 0xc0001b4870, 0xb34f40, 0xc001a03530, 0x0, 0x0, 0x0, ...)
	/app/collector.go:133 +0x5be
main.collector.Collect(0xb40660, 0xc0019feb00, 0xc000820011, 0xe, 0xc0001b4870, 0xb34f40, 0xc001a03530, 0xc0000786c0)
	/app/collector.go:222 +0xbc
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:457 +0x5ce

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f41afd73fa8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00117a218, 0x72, 0x0, 0x0, 0xa85b68)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00117a200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc00117a200, 0x1638e0807e178001, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc001130560, 0x62a1af5d, 0xc0017c5ad0, 0x48e3a6)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc001130560, 0xc0017c5b20, 0x18, 0xc000000300, 0x7f8dec)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc0012b4000, 0xb3ee20, 0xc001130560, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2937 +0x266
github.com/prometheus/exporter-toolkit/web.Serve(0xb3ee20, 0xc001130560, 0xc0012b4000, 0x0, 0x0, 0xb34f40, 0xc000151f50, 0x0, 0xe0)
	/go/pkg/mod/github.com/prometheus/exporter-toolkit@v0.5.1/web/tls_config.go:192 +0x1b0
github.com/prometheus/exporter-toolkit/web.ListenAndServe(0xc0012b4000, 0x0, 0x0, 0xb34f40, 0xc000151f50, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/exporter-toolkit@v0.5.1/web/tls_config.go:184 +0xfd
main.main()
	/app/main.go:248 +0xb71

goroutine 49 [syscall]:
os/signal.signal_recv(0xc0015f2230)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 50 [select]:
main.main.func1(0xc000078360, 0xb34f40, 0xc000151f50)
	/app/main.go:179 +0xe5
created by main.main
	/app/main.go:177 +0x7ce

goroutine 54 [select]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0019f1860, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:513 +0xbbc
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/promhttp/http.go:126 +0x99
net/http.HandlerFunc.ServeHTTP(0xc0017bca80, 0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/usr/local/go/src/net/http/server.go:2042 +0x44
main.handler(0xb3f0a0, 0xc0011c2000, 0xc000216300, 0xb34f40, 0xc000151f50)
	/app/main.go:110 +0x6d7
main.main.func2(0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/app/main.go:201 +0x51
net/http.HandlerFunc.ServeHTTP(0xc001130460, 0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xea0040, 0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0012b4000, 0xb3f0a0, 0xc0011c2000, 0xc000216300)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0001900a0, 0xb40660, 0xc001250280)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7f41afd73ec0, 0x72, 0xb36220)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00117a398, 0x72, 0xb36200, 0xe444f0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00117a380, 0xc0001830f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc00117a380, 0xc0001830f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000832ad8, 0xc0001830f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
net/http.(*connReader).backgroundRead(0xc0001830e0)
	/usr/local/go/src/net/http/server.go:690 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:686 +0xd5

goroutine 12 [semacquire]:
sync.runtime_Semacquire(0xc0011b3c08)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0011b3c00)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0011b3c00, 0xc0000786c0, 0xc000078720)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:463 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:462 +0x60d
���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
`

my generator Yaml File looks like this:

`modules:
  # Default IF-MIB interfaces table with ifIndex.
  if_mib:
    walk: [sysUpTime, interfaces, ifXTable]

    version: 3  # SNMP version to use. Defaults to 2.
                  # 1 will use GETNEXT, 2 and 3 use GETBULK.
    max_repetitions: 25  # How many objects to request with GET/GETBULK, defaults to 25.
                          # May need to be reduced for buggy devices.
    retries: 3   # How many times to retry a failed request, defaults to 3.
    timeout: 5s  # Timeout for each individual SNMP request, defaults to 5s.

    auth:
      # Community string is used with SNMP v1 and v2. Defaults to "public".
      community: public

      username: snmp_exporter_Prometheus  # Required, no default. -u option to NetSNMP.
      security_level: authPriv  # Defaults to noAuthNoPriv. -l option to NetSNMP.
                                      # Can be noAuthNoPriv, authNoPriv or authPriv.
      password: [auth pw]  # Has no default. Also known as authKey, -A option to NetSNMP.
                        # Required if security_level is authNoPriv or authPriv.
      auth_protocol: MD5  # MD5, SHA, SHA224, SHA256, SHA384, or SHA512. Defaults to MD5. -a option to NetSNMP.
                            # Used if security_level is authNoPriv or authPriv.
      priv_protocol: DES  # DES, AES, AES192, or AES256. Defaults to DES. -x option to NetSNMP.
                            # Used if security_level is authPriv.
      priv_password: [priv pw]# Has no default. Also known as privKey, -X option to NetSNMP.
                                # Required if security_level is authPriv.

    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        # Uis OID to avoid conflict with PaloAlto PAN-COMMON-MIB.
        lookup: 1.3.6.1.2.1.2.2.1.2 # ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName
    overrides:
      ifAlias:
        ignore: true # Lookup metric
      ifDescr:
        ignore: true # Lookup metric
      ifName:
        ignore: true # Lookup metric
      ifType:
        type: EnumAsInfo`

I hope someone can help with that Problem!

**Comment by IAmMrTh** [comment]
The problem could be fixed by adjusting the settings of the switch. I changed the Algorithm to SHA and added the Prometheus IP to the Trap Config.
